/**
 * robots.txt — generated by Next.js's MetadataRoute.Robots.
 *
 * Goals:
 *   1. Default rule: allow everything except internal surfaces
 *      (dashboard, admin-login, internal API).
 *   2. Explicit allow rules for AI crawlers (GEO surface) — listing them
 *      explicitly ensures their documentation teams see the allow and
 *      doesn't accidentally crawl `/dashboard/` (they would 401/403
 *      anyway, but the cleaner signal helps).
 *   3. Point to llms.txt and the sitemap so the crawlers can ingest
 *      everything we want indexed.
 *
 * Crawler allow-list sources (last reviewed Aug 2026):
 *   - OpenAI:     GPTBot, OAI-SearchBot, ChatGPT-User
 *   - Anthropic:  ClaudeBot, Claude-User, Claude-SearchBot
 *   - Perplexity: PerplexityBot, Perplexity-User
 *   - Google:     Google-Extended (Gemini / AI Overviews training)
 *   - Common Crawl: CCBot
 *   - AWS:        AmazonBedrock, NovaBot
 *   - Meta:       Meta-ExternalAgent, Meta-ExternalFetcher
 *   - Mistral:    MistralAI-User
 *   - xAI:        xAI
 *   - DeepSeek:   DeepSeekBot
 *   - Apple:      Applebot-Extended
 *   - ByteDance:  Bytespider
 */

import type { MetadataRoute } from 'next';

const SITEMAP = 'https://elitefightuniverse.com/sitemap.xml';
const LLMS_TXT = 'https://elitefightuniverse.com/llms.txt';
const LLMS_FULL = 'https://elitefightuniverse.com/llms-full.txt';

const AI_CRAWLERS = [
  'GPTBot',
  'OAI-SearchBot',
  'ChatGPT-User',
  'ClaudeBot',
  'Claude-User',
  'Claude-SearchBot',
  'anthropic-ai',
  'PerplexityBot',
  'Perplexity-User',
  'Google-Extended',
  'GoogleOther',
  'Googlebot',
  'CCBot',
  'AmazonBedrock',
  'NovaBot',
  'Meta-ExternalAgent',
  'Meta-ExternalFetcher',
  'MistralAI-User',
  'xAI',
  'DeepSeekBot',
  'Applebot-Extended',
  'Bytespider',
  'cohere-ai',
  'cohere-training-data-crawler',
];

const DISALLOW_INTERNAL = ['/dashboard/', '/dashboard/*', '/admin-login/', '/api/'];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      // Default: allow public, block internal surfaces.
      {
        userAgent: '*',
        allow: ['/', '/llms.txt', '/llms-full.txt'],
        disallow: DISALLOW_INTERNAL,
      },
      // Explicit allow for each AI crawler — makes intent unambiguous.
      ...AI_CRAWLERS.map((userAgent) => ({
        userAgent,
        allow: ['/', '/llms.txt', '/llms-full.txt'],
        disallow: DISALLOW_INTERNAL,
      })),
    ],
    sitemap: [SITEMAP, LLMS_TXT, LLMS_FULL],
    host: 'https://elitefightuniverse.com',
  };
}
